apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-api
  labels:
    app: house-price-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: house-price-api
    spec:
      containers:
        - name: house-price-api
          image: ghcr.io/wanda-lily/bda-house-price-mlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_PATH
              value: "model/price_model.pkl"
          #is application alive
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          #is apllication ready
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "3Gi"
              cpu: "500m"
