apiVersion: v1
kind: Service
metadata:
  name: house-price-api-svc
spec:
  type: NodePort
  selector:
    app: house-price-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
